import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'
import Provider from "./Provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
          <Toaster/>
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}